### ISSUE TITLE
Html5TestSanitizer script_tag_with_multiple_open_brackets test fails

### ISSUE THREAD

**Issue by ktdreyer** [flavorjones/loofah#97]
I get the following test suite failure on Fedora 24:

```
$ ruby -Ilib:test -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /builddir/build/BUILD/loofah-2.0.3/usr/share/gems/gems/loofah-2.0.3/test/helper.rb:2:in `<top (required)>'
  /builddir/build/BUILD/loofah-2.0.3/usr/share/gems/gems/loofah-2.0.3/test/unit/test_scrubber.rb:1:in `<top (required)>'
  -e:1:in `glob'
  -e:1:in `<main>'
=> testing with Nokogiri {"warnings"=>[], "nokogiri"=>"1.6.7.rc3", "ruby"=>{"version"=>"2.2.4", "platform"=>"x86_64-linux", "description"=>"ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]", "engine"=>"ruby"}, "libxml"=>{"binding"=>"extension", "source"=>"system", "compiled"=>"2.9.3", "loaded"=>"2.9.3"}}
Run options: --seed 51789

# Running:

.......S............................................................................................................................................................................................................................................................................................................................................................................................................................S.........................................................................................................................................................................................................S..........F......................................................................................................................................................................S..............

Finished in 0.268979s, 3029.9779 runs/s, 3424.0610 assertions/s.

  1) Failure:
Html5TestSanitizer#test_0051_testdata sanitizer should_sanitize_script_tag_with_multiple_open_brackets [/builddir/build/BUILD/loofah-2.0.3/usr/share/gems/gems/loofah-2.0.3/test/html5/test_sanitizer.rb:30]:
given:    "<<script>alert("XSS");//<</script>"
expected: "alert('XSS');//"
got:      "&lt;&lt;script&gt;alert('XSS');//&lt;&lt;/script&gt;"

815 runs, 921 assertions, 1 failures, 0 errors, 4 skips
```

**Comment by ktdreyer** [comment]
(I'm using Loofah 2.0.3)

**Comment by flavorjones** [comment]
Hi,

This has already been fixed on master, and is related to a behavior change from libxml 2.9.2 to 2.9.3.

**Comment by ktdreyer** [comment]
Thanks! Mind releasing a new version with this change?

**Comment by flavorjones** [comment]
I've cut v2.1.0.rc2, which is up on rubygems.org now.

**Comment by ktdreyer** [comment]
Thanks!

**Comment by ktdreyer** [comment]
For the record, the issue was originally reported @ https://github.com/flavorjones/loofah/issues/96
